version: "3.8"
services:
    yifsql:
        container_name: yifsql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "YIF_Backend_DB_MyKeyOnlyInMyHeart"
            MSSQL_PID: "Express"
    yifbackend:
        container_name: yifbackend
        image: smethan/yifbackend:latest
        build:
            context: .
            dockerfile: Dockerfile.VM
        ports:
            - "5000:80"
        restart: always
        depends_on:
            - yifsql